# Generated by Django 3.2.9 on 2021-12-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('prefix', models.CharField(max_length=255, verbose_name='Prefijo')),
                ('value', models.IntegerField(verbose_name='Consecutivo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects')),
            ],
            options={
                'verbose_name': 'Consecutivo',
                'verbose_name_plural': 'Consecutivos',
            },
        ),
    ]
