# Generated by Django 3.2.9 on 2021-12-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0002_counters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counters',
            unique_together={('name', 'project')},
        ),
    ]
