# Generated by Django 3.2.9 on 2022-01-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0004_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_timeline', to='mcd_site.projects', verbose_name='Proyecto'),
        ),
    ]
