# Generated by Django 3.2.9 on 2022-02-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0005_timeline_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('name', 'project')},
        ),
    ]
