# Generated by Django 3.2.9 on 2022-03-13 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd_site', '0006_auto_20220207_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_by_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.ManyToManyField(to='mcd_site.Projects', verbose_name='Proyectos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proyectos por usuario',
                'verbose_name_plural': 'Proyectos por usuarios',
            },
        ),
    ]
