# Generated by Django 3.2.9 on 2022-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0007_users_by_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='projects',
            field=models.ManyToManyField(to='mcd_site.Projects', verbose_name='Proyectos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='force_change_pswd',
            field=models.BooleanField(default=1, help_text='Selecciona esta opcion para que el usuario deba cambiar su contraseña en el proximo inicio de sesión', verbose_name='Forzar cambio de contraseña'),
        ),
        migrations.DeleteModel(
            name='Users_by_project',
        ),
    ]
