# Generated by Django 3.2.9 on 2022-03-15 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd_site', '0008_auto_20220313_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
                ('users_to_send', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios a enviar')),
            ],
            options={
                'verbose_name': 'Notificaciones por email',
            },
        ),
    ]
