# Generated by Django 3.2.13 on 2022-04-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0009_notifications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Foto'),
        ),
    ]
