# Generated by Django 3.2.20 on 2023-09-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0010_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='text_ds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto resolucion documento soporte DIAN'),
        ),
    ]
