# Generated by Django 3.2.25 on 2025-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0011_projects_text_ds'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
