# Generated by Django 3.2.25 on 2025-07-10 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd_site', '0012_parameters_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='default_admin_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_admin_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
