# Generated by Django 3.2.25 on 2025-07-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0013_projects_default_admin_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos', verbose_name='Logo empresa'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(upload_to='project_logos', verbose_name='Logo proyecto'),
        ),
    ]
