"""
Django settings for mcd_project project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def get_bool_env(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def get_list_env(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def get_path_env(name, default):
    value = os.getenv(name)
    if not value:
        return Path(default)
    path = Path(value)
    return path if path.is_absolute() else BASE_DIR / path


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure--l3ik$wfev+oc1e@q4)tys_l2-awmld*r85dpc5hs9vm9vxm(b',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DEBUG', True)

ALLOWED_HOSTS = get_list_env('ALLOWED_HOSTS', '*')
APP_DOMAIN = os.getenv('APP_DOMAIN', '')
CSRF_TRUSTED_ORIGINS = get_list_env(
    'CSRF_TRUSTED_ORIGINS',
    f'https://{APP_DOMAIN}' if APP_DOMAIN else '',
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)

# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_forms_semantic_ui',
    'django_cron',
    'mcd_site.apps.McdSiteConfig',
    'terceros',
    'sales',
    'finance',
]

USE_S3_MEDIA = get_bool_env('USE_S3_MEDIA', False)
if USE_S3_MEDIA:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'mcd_site.middleware.DoubleSubmitProtectionMiddleware',  # Añadir aquí
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mcd_site.middleware.EnsureUserProfileMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mcd_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcd_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DB_HOST = os.getenv('DB_HOST', 'db')
#DB_HOST = '93.188.161.177'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME', 'macardyapp'),
        'USER': os.getenv('DB_USER', 'mcduser'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'mcduser'),
        'HOST': DB_HOST,
        'PORT': os.getenv('DB_PORT', '')
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ADMINS = [
    (
        os.getenv('ADMIN_NAME', '2asoft'),
        os.getenv('ADMIN_EMAIL', '2asoftcol@gmail.com'),
    ),
]

# Configuración de emails mejorada
DELIVERY_ALERT_EMAILS = get_list_env(
    'DELIVERY_ALERT_EMAILS',
    'jorgeavila@somosandina.co,jmavila330@gmail.com',
)

# Configuración SMTP con fallback
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.2asoft.tech')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'macardyapp@2asoft.tech')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', ';odt}DgTS268=1>P')
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', True)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))  # Timeout en segundos
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'MacardyApp - 2ASoft <macardyapp@2asoft.tech>',
)

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/tmp/delivery_alerts.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'gunicorn.error': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.access': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'sales.management.commands.notify_delivery_deadlines': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static_files'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
if not MEDIA_URL.endswith('/'):
    MEDIA_URL += '/'

LOCAL_MEDIA_ROOT = get_path_env('LOCAL_MEDIA_ROOT', BASE_DIR / 'static_media')
MEDIA_ROOT = LOCAL_MEDIA_ROOT
TMP_MEDIA_PREFIX = os.getenv('TMP_MEDIA_PREFIX', 'tmp/')
TMP_MEDIA_PREFIX = TMP_MEDIA_PREFIX.strip('/') + '/'
TMP_MEDIA_ROOT = get_path_env('TMP_MEDIA_ROOT', LOCAL_MEDIA_ROOT / 'tmp')
TMP_MEDIA_URL = os.getenv('TMP_MEDIA_URL', f"{MEDIA_URL}{TMP_MEDIA_PREFIX}")
if not TMP_MEDIA_URL.endswith('/'):
    TMP_MEDIA_URL += '/'

AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', '')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_DEFAULT_ACL = os.getenv('AWS_DEFAULT_ACL', 'public-read')
AWS_QUERYSTRING_AUTH = get_bool_env('AWS_QUERYSTRING_AUTH', False)
AWS_S3_FILE_OVERWRITE = get_bool_env('AWS_S3_FILE_OVERWRITE', False)
AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'path')
AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION', 's3v4')
PERSISTENT_MEDIA_BASE_URL = os.getenv(
    'PERSISTENT_MEDIA_BASE_URL',
    f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/" if AWS_S3_ENDPOINT_URL and AWS_STORAGE_BUCKET_NAME else MEDIA_URL,
)
if not PERSISTENT_MEDIA_BASE_URL.endswith('/'):
    PERSISTENT_MEDIA_BASE_URL += '/'

if USE_S3_MEDIA:
    DEFAULT_FILE_STORAGE = 'mcd_project.storage_backends.PublicMediaStorage'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# django-registration-redux
ACCOUNT_ACTIVATION_DAYS = 7
SITE_ID = 1
LOGIN_REDIRECT_URL = '/landing'

# crispy-forms
CRISPY_TEMPLATE_PACK = 'semantic-ui'
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap', 'uni_form', 'bootstrap3',
                                 'bootstrap4', 'semantic-ui',)

# Cache para tokens de doble submit
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'double-submit-protection',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Máximo 1000 tokens en cache
        }
    }
}
