# Generated by Django 3.2.9 on 2022-01-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcd_site', '0004_parameters'),
        ('sales', '0009_assigned_comission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=255, verbose_name='Recibo')),
                ('add_date', models.DateField(verbose_name='Fecha de registro')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_incomes', to='mcd_site.projects', verbose_name='Proyecto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_income', to='sales.sales', verbose_name='Venta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recaudos',
            },
        ),
        migrations.CreateModel(
            name='Incomes_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Interés corriente')),
                ('others', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Otros')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Mora')),
                ('arrears_days', models.IntegerField(verbose_name='Mora')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomes', verbose_name='Ingresos')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.payment_plans', verbose_name='Cuota pagada')),
            ],
            options={
                'verbose_name': 'Recaudos',
            },
        ),
    ]
