# Generated by Django 3.2.9 on 2022-01-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0004_parameters'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AddField(
            model_name='incomes',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finance.payment_methods', verbose_name='Forma de pago'),
            preserve_default=False,
        ),
    ]
