# Generated by Django 3.2.9 on 2022-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0004_parameters'),
        ('finance', '0002_auto_20220105_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='receipt',
            field=models.IntegerField(verbose_name='Recibo'),
        ),
        migrations.AlterUniqueTogether(
            name='incomes',
            unique_together={('receipt', 'project')},
        ),
    ]
