# Generated by Django 3.2.9 on 2022-01-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_assigned_comission'),
        ('finance', '0003_auto_20220107_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Anulado', 'Anulado')], default='Aprobado', max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_income', to='sales.sales', verbose_name='Venta'),
        ),
    ]
