# Generated by Django 3.2.9 on 2022-01-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_assigned_comission'),
        ('finance', '0004_auto_20220112_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='status',
        ),
        migrations.AlterField(
            model_name='incomes',
            name='sale',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, related_name='sale_income', to='sales.sales', verbose_name='Venta'),
            preserve_default=False,
        ),
    ]
