# Generated by Django 3.2.9 on 2022-01-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20220112_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='receipt',
            field=models.CharField(max_length=20, verbose_name='Recibo'),
        ),
    ]
