# Generated by Django 3.2.9 on 2022-01-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_assigned_comission'),
        ('finance', '0006_alter_incomes_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector_per_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_collector_sale', to=settings.AUTH_USER_MODEL, verbose_name='Gestor de cobro asignado')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_collector', to='sales.sales', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Gestor de cobro por venta',
                'verbose_name_plural': 'Gestores de cobro por ventas',
            },
        ),
    ]
