# Generated by Django 3.2.9 on 2022-01-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_assigned_comission'),
        ('finance', '0007_collector_per_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector_per_sale',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_collector', to='sales.sales', verbose_name='Contrato'),
        ),
    ]
