# Generated by Django 3.2.9 on 2022-01-18 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20220118_1344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_alter_collector_per_sale_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_info',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.payment_plans',),
        ),
        migrations.CreateModel(
            name='Sales_extra_info',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.sales',),
        ),
        migrations.CreateModel(
            name='Collection_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('Cobro', 'Cobro'), ('Saludo', 'Saludo'), ('Otro', 'Otro')], max_length=500, verbose_name='Tipo de seguimiento')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_colleciton_feed', to='sales.sales', verbose_name='Contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_collection_feed', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimientos de cartera',
            },
        ),
    ]
