# Generated by Django 3.2.9 on 2022-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_collection_feed_credit_info_sales_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_feed',
            name='comment',
            field=models.CharField(default='', max_length=500, verbose_name='Comentario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection_feed',
            name='comment_type',
            field=models.CharField(choices=[('Cobro', 'Cobro'), ('Saludo', 'Saludo'), ('Otro', 'Otro')], max_length=100, verbose_name='Tipo de seguimiento'),
        ),
    ]
