# Generated by Django 3.2.9 on 2022-02-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_backup_payment_plans_backup_date'),
        ('finance', '0010_auto_20220118_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissions_Payment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.assigned_comission',),
        ),
        migrations.AlterField(
            model_name='incomes_detail',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.payment_plans', verbose_name='Cuota pagada'),
        ),
    ]
