# Generated by Django 3.2.9 on 2022-02-23 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceros', '0005_sellers_pay_pmt'),
        ('mcd_site', '0006_auto_20220207_2151'),
        ('finance', '0011_auto_20220213_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(verbose_name='Fecha')),
                ('observations', models.CharField(max_length=255, verbose_name='Observaciones')),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aporbado')], max_length=255, verbose_name='Estado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registra')),
            ],
            options={
                'verbose_name': 'PMT',
                'verbose_name_plural': 'PMTs',
            },
        ),
        migrations.CreateModel(
            name='PMT_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('pmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.pmt', verbose_name='PMT asociado')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_pmt', to='terceros.sellers', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'PMT detalle',
                'verbose_name_plural': 'PMTs detalle',
            },
        ),
    ]
