# Generated by Django 3.2.9 on 2022-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_pmt_pmt_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmt',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
