# Generated by Django 3.2.9 on 2022-02-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0006_auto_20220207_2151'),
        ('finance', '0013_alter_pmt_add_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmt',
            unique_together={('project', 'add_date')},
        ),
    ]
