# Generated by Django 3.2.9 on 2022-02-24 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0014_alter_pmt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmt',
            name='user_approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_approve_pmt', to=settings.AUTH_USER_MODEL, verbose_name='Usuario aprueba'),
        ),
    ]
