# Generated by Django 3.2.9 on 2022-03-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_pmt_user_approve'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment_methods',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payment_methods',
            name='project',
        ),
    ]
