# Generated by Django 3.2.9 on 2022-03-06 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0006_auto_20220207_2151'),
        ('sales', '0019_alter_assigned_comission_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0016_auto_20220305_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_collection', to='mcd_site.projects', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_collection_budget', to=settings.AUTH_USER_MODEL, verbose_name='Usuario carga')),
            ],
            options={
                'verbose_name': 'Presupuesto de cartera',
                'verbose_name_plural': 'Presupuestos de cartera',
                'unique_together': {('project', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Collection_budget_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt_30', models.FloatField(default=0, verbose_name='<30')),
                ('lt_60', models.FloatField(default=0, verbose_name='<60')),
                ('lt_90', models.FloatField(default=0, verbose_name='<90')),
                ('lt_120', models.FloatField(default=0, verbose_name='<120')),
                ('gt_120', models.FloatField(default=0, verbose_name='>120')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.collection_budget', verbose_name='Id Presupuesto')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sales', verbose_name='Venta')),
            ],
        ),
    ]
