# Generated by Django 3.2.9 on 2022-03-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_assigned_comission_state'),
        ('finance', '0017_collection_budget_collection_budget_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection_budget_detail',
            options={'verbose_name': 'Presupuesto de cartera - detalle', 'verbose_name_plural': 'Presupuestos de cartera - detalles'},
        ),
        migrations.AlterUniqueTogether(
            name='collection_budget_detail',
            unique_together={('budget', 'sale')},
        ),
    ]
