# Generated by Django 3.2.9 on 2022-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20220305_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255, unique=True, verbose_name='Numero de cuenta')),
                ('nit_to_pay', models.IntegerField(verbose_name='Nit empresa pagadora')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
    ]
