# Generated by Django 3.2.9 on 2022-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_payment_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_accounts',
            name='account_type',
            field=models.CharField(choices=[('S', 'Ahorros'), ('D', 'Corriente')], default='D', max_length=10, verbose_name='Tipo de cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_accounts',
            name='account_number',
            field=models.BigIntegerField(unique=True, verbose_name='Numero de cuenta'),
        ),
    ]
