# Generated by Django 3.2.9 on 2022-03-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0009_notifications_email'),
        ('finance', '0020_auto_20220311_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('percentage', models.FloatField(verbose_name='Porcentaje')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'unique_together': {('name', 'project')},
            },
        ),
    ]
