# Generated by Django 3.2.9 on 2022-03-20 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd_site', '0009_notifications_email'),
        ('finance', '0021_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cc', to='mcd_site.projects', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='expenses_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha gasto')),
                ('description', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('costcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_expenses', to='finance.cost_center', verbose_name='Centro de costo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_expense', to='mcd_site.projects', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registra')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
