# Generated by Django 3.2.9 on 2022-03-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_auto_20220320_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses_detail',
            old_name='fecha',
            new_name='date',
        ),
    ]
