# Generated by Django 3.2.13 on 2022-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_rename_fecha_expenses_detail_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes',
            options={'verbose_name': 'Recaudo', 'verbose_name_plural': 'Recaudos'},
        ),
        migrations.AddField(
            model_name='cost_center',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo desde'),
        ),
        migrations.AddField(
            model_name='cost_center',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo hasta'),
        ),
        migrations.AlterUniqueTogether(
            name='cost_center',
            unique_together=set(),
        ),
    ]
