# Generated by Django 3.2.20 on 2023-08-30 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20220426_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomes_detail',
            options={'verbose_name': 'Recaudo detallado', 'verbose_name_plural': 'Recaudos detallados'},
        ),
        migrations.AddField(
            model_name='incomes',
            name='pm1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FP1', to='finance.payment_methods', verbose_name='Forma de pago 1'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='pm2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FP2', to='finance.payment_methods', verbose_name='Forma de pago 2'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='value1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor FP1'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='value2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor FP2'),
        ),
    ]
