# Generated by Django 3.2.20 on 2023-08-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20230829_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='obs_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacion 1'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='obs_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacion 2'),
        ),
    ]
