# Generated by Django 3.2.20 on 2023-09-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0027_incomes_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='Fecha aprovación')),
                ('status', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=255)),
                ('user_approve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_approve', to=settings.AUTH_USER_MODEL, verbose_name='Usuario aprueba')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicita')),
            ],
            options={
                'verbose_name': 'Presupuesto comercial',
                'verbose_name_plural': 'Presupuestos comerciales',
            },
        ),
        migrations.CreateModel(
            name='Commercial_budget_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor solicitado')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.commercial_budget', verbose_name='Solicitud')),
            ],
        ),
    ]
