# Generated by Django 3.2.20 on 2023-11-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0011_projects_text_ds'),
        ('finance', '0028_commercial_budget_commercial_budget_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects'),
        ),
    ]
