# Generated by Django 3.2.25 on 2025-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_commercial_budget_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_budget_detail',
            name='portfolio_type',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('administrativa', 'Administrativa')], default='commercial', max_length=20, verbose_name='Portfolio type'),
        ),
    ]
