# Generated by Django 3.2.25 on 2025-07-02 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0011_projects_text_ds'),
        ('sales', '0028_alter_comission_position_advance_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0030_collection_budget_detail_portfolio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('payment_date', models.DateField(verbose_name='Fecha estimada de pago')),
                ('value', models.IntegerField(verbose_name='Valor total')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Valor FP1')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Valor FP2')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('obs_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación 1')),
                ('obs_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación 2')),
                ('soporte', models.FileField(blank=True, null=True, upload_to='soportes_recibos/', verbose_name='Soporte')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('ajuste', 'Requiere Ajuste')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones_revision', models.TextField(blank=True, null=True, verbose_name='Notas de tesorería')),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.payment_methods', verbose_name='Forma de pago principal')),
                ('pm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sol_fp1', to='finance.payment_methods', verbose_name='Forma de pago 1')),
                ('pm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sol_fp2', to='finance.payment_methods', verbose_name='Forma de pago 2')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_recibo_proyecto', to='mcd_site.projects', verbose_name='Proyecto')),
                ('recibo_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='finance.incomes', verbose_name='Recibo generado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_recibo_venta', to='sales.sales', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Recibo',
                'verbose_name_plural': 'Solicitudes de Recibo',
            },
        ),
    ]
