# Generated by Django 3.2.25 on 2025-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_solicitudrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecibo',
            name='arrears_condonate',
            field=models.IntegerField(default=0, verbose_name='Condonación mora (%)'),
        ),
        migrations.AddField(
            model_name='solicitudrecibo',
            name='capital_payment',
            field=models.BooleanField(default=False, help_text='Marcar si es un abono directo a capital', verbose_name='Abono a capital'),
        ),
    ]
