# Generated by Django 3.2.25 on 2025-07-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20250702_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecibo',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='solicitudrecibo',
            name='value',
        ),
    ]
