# Generated by Django 3.2.25 on 2025-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20250702_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecibo',
            name='capital_payment',
            field=models.BooleanField(default=False, help_text='El abono a capital se aplicará despues de pagar las cuotas vencidas.', verbose_name='Abono a capital'),
        ),
        migrations.AlterField(
            model_name='solicitudrecibo',
            name='payment_date',
            field=models.DateField(verbose_name='Fecha real de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudrecibo',
            name='value1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor FP1'),
        ),
        migrations.AlterField(
            model_name='solicitudrecibo',
            name='value2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor FP2'),
        ),
    ]
