# Generated by Django 3.2.25 on 2025-07-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20250702_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecibo',
            name='condonacion_autorizada',
            field=models.BooleanField(default=False),
        ),
    ]
