# Generated by Django 3.2.25 on 2025-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_solicitudrecibo_condonacion_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecibo',
            name='tipo_abono_capital',
            field=models.CharField(blank=True, choices=[('', '---------'), ('reducir_tiempo', 'Abono con reducción de tiempo'), ('reducir_cuota', 'Abono con reducción de cuota'), ('cuotas_futuras', 'Abono a cuotas futuras')], default='', max_length=20),
        ),
    ]
