# Generated by Django 3.2.25 on 2025-07-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_comission_position_advance_bonus'),
        ('finance', '0036_solicitudrecibo_tipo_abono_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('', '---------'), ('reducir_tiempo', 'Abono con reducción de tiempo'), ('reducir_cuota', 'Abono con reducción de cuota'), ('cuotas_futuras', 'Abono a cuotas futuras')], default='', max_length=20, verbose_name='Tipo de abono')),
                ('capital_aplicado', models.FloatField(verbose_name='Capital aplicado')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cuotas_afectadas', models.IntegerField()),
                ('nueva_cuota', models.FloatField(blank=True, null=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.incomes')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sales')),
            ],
        ),
    ]
