# Generated by Django 3.2.25 on 2025-07-06 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0037_abonocapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecibo',
            name='condonacion_autorizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condonacion_autorizada_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
