# Generated by Django 3.2.25 on 2025-07-07 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0038_solicitudrecibo_condonacion_autorizada_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionGestorCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cartera', models.CharField(choices=[('comercial', 'Comercial'), ('administrativa', 'Administrativa')], max_length=50)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
