# Generated by Django 3.2.25 on 2025-07-08 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0039_comisiongestorcartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocapital',
            name='comision_pagado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos_pagados_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonocapital',
            name='comision_pagado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonocapital',
            name='comision_pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos_pagados_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonocapital',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='abonocapital',
            name='valor_comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
