# Generated by Django 3.2.25 on 2025-07-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_convert_to_foreignkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection_feed',
            options={'verbose_name': 'Seguimiento de cartera', 'verbose_name_plural': 'Seguimientos de cartera'},
        ),
    ]
