# Generated by Django 3.2.25 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_alter_collection_feed_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecibo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('ajuste', 'Requiere Ajuste')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
