# Generated by Django 3.2.9 on 2021-12-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcd_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_document', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Documento cliente')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('marital_status', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Union Libre', 'Union Libre')], max_length=255, null=True, verbose_name='Estado Civil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('city', models.IntegerField(blank=True, null=True, verbose_name='Ciudad de Residencia')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='Departamento')),
                ('country', models.IntegerField(blank=True, null=True, verbose_name='País')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_document', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Documento vendedor')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de residencia')),
                ('city', models.IntegerField(blank=True, null=True, verbose_name='Ciudad de residencia')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='Departamento')),
                ('country', models.IntegerField(blank=True, null=True, verbose_name='País')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Sellers', verbose_name='Hoja de vida')),
                ('rut_support', models.FileField(blank=True, null=True, upload_to='Sellers', verbose_name='RUT')),
                ('bank_certificate', models.FileField(blank=True, null=True, upload_to='Sellers', verbose_name='Certificado bancario')),
                ('account_type', models.CharField(choices=[('S', 'Ahorros'), ('D', 'Corriente')], max_length=255, verbose_name='Tipo de cuenta')),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_type', models.CharField(choices=[('I', 'Interno'), ('E', 'Externo')], max_length=255, verbose_name='Tipo de vendedor')),
                ('seller_state', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=255, verbose_name='Tipo de vendedor')),
                ('retencion', models.FloatField(default=10)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('marital_status', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Union Libre', 'Union Libre')], max_length=255, null=True, verbose_name='Estado Civil')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('bank_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.bank_entities', verbose_name='Entidad Bancaria')),
                ('projects', models.ManyToManyField(to='mcd_site.Projects', verbose_name='Proyectos')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
    ]
