# Generated by Django 3.2.9 on 2022-01-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='house_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono de Residencia'),
        ),
        migrations.AddField(
            model_name='clients',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion oficina'),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone_office',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono de Oficina'),
        ),
    ]
