# Generated by Django 3.2.9 on 2022-02-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20220125_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_client', to='terceros.sellers', verbose_name='Captado por'),
        ),
    ]
