# Generated by Django 3.2.9 on 2022-02-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_clients_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
