# Generated by Django 3.2.9 on 2022-02-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_alter_sellers_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='pay_pmt',
            field=models.BooleanField(default=1, verbose_name='Se paga PMT'),
            preserve_default=False,
        ),
    ]
