# Generated by Django 3.2.9 on 2022-04-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0009_notifications_email'),
        ('terceros', '0005_sellers_pay_pmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(max_length=255, verbose_name='Cedula')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de residencia')),
                ('city', models.IntegerField(blank=True, null=True, verbose_name='Ciudad de residencia')),
                ('country', models.IntegerField(blank=True, null=True, verbose_name='País')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Collaborators', verbose_name='Hoja de vida')),
                ('contract_support', models.FileField(blank=True, null=True, upload_to='Collaborators', verbose_name='Contrato')),
                ('bank_certificate', models.FileField(blank=True, null=True, upload_to='Collaborators', verbose_name='Certificado bancario')),
                ('account_type', models.CharField(choices=[('S', 'Ahorros'), ('D', 'Corriente')], max_length=255, verbose_name='Tipo de cuenta')),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Inactivo', 'Inactivo')], default='Activo', max_length=255, verbose_name='Tipo de vendedor')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('bank_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.bank_entities', verbose_name='Entidad Bancaria')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Collaborator_contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contract', models.CharField(choices=[('Fijo', 'Fijo'), ('Obra labor', 'Obra labor'), ('Indefinido', 'Indefinido'), ('Prestación de servicios', 'Prestación de servicios')], max_length=255, verbose_name='Tipo de contrado')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración')),
                ('initial_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('salary', models.IntegerField(verbose_name='Salario')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.collaborators', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Contrato colaborador',
                'verbose_name_plural': 'Contratos colaboradores',
            },
        ),
    ]
