# Generated by Django 3.2.9 on 2022-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0006_collaborator_contracts_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='scholarity',
            field=models.CharField(choices=[('Bachillerato', 'Bachillerato'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado'), ('Maestria', 'Maestria')], default='Bachillerato', max_length=255, verbose_name='Escolaridad'),
            preserve_default=False,
        ),
    ]
