# Generated by Django 3.2.9 on 2022-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_collaborators_scholarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator_contracts',
            name='position_name',
            field=models.CharField(default='Mensajero', max_length=255, verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
