# Generated by Django 3.2.9 on 2022-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0008_collaborator_contracts_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Inactivo', 'Inactivo')], default='Activo', max_length=255, verbose_name='Tipo de vendedor'),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='state',
            field=models.IntegerField(blank=True, null=True, verbose_name='Departamento'),
        ),
    ]
