# Generated by Django 3.2.9 on 2022-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0009_auto_20220418_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='cesantias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborators',
            name='eps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborators',
            name='pension',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
