# Generated by Django 3.2.13 on 2022-04-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0010_alter_perfil_avatar'),
        ('terceros', '0010_auto_20220419_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Grupo de venta',
                'verbose_name_plural': 'Grupos de venta',
            },
        ),
        migrations.AddField(
            model_name='sellers',
            name='sales_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros.sellers_groups', verbose_name='Grupo de ventas'),
        ),
    ]
