# Generated by Django 3.2.13 on 2022-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0011_auto_20220428_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers_groups',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
