# Generated by Django 3.2.13 on 2022-04-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0010_alter_perfil_avatar'),
        ('terceros', '0012_alter_sellers_groups_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellers_groups',
            unique_together={('name', 'project')},
        ),
    ]
