# Generated by Django 3.2.13 on 2022-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0013_alter_sellers_groups_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers_groups',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
