# Generated by Django 3.2.13 on 2022-05-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0014_sellers_groups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator_contracts',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
    ]
