# Generated by Django 3.2.13 on 2022-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0015_collaborator_contracts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado')], default='Activo', max_length=255, verbose_name='Estado'),
        ),
    ]
