# Generated by Django 3.2.13 on 2022-05-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0016_alter_collaborators_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='collaborators_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('load_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('file', models.FileField(upload_to='Collaborators', verbose_name='Archivo')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.collaborators')),
            ],
            options={
                'verbose_name': 'Archivo colaborador',
                'verbose_name_plural': 'Archivos colaboradores',
            },
        ),
    ]
