# Generated by Django 3.2.13 on 2022-06-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0017_collaborators_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='id_document',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller_state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=255, verbose_name='Estado'),
        ),
    ]
