# Generated by Django 3.2.13 on 2022-07-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0018_auto_20220614_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='house_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Residencia'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Oficina'),
        ),
    ]
