# Generated by Django 3.2.13 on 2022-07-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0019_auto_20220712_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborators_files',
            unique_together={('collaborator', 'description')},
        ),
    ]
