# Generated by Django 3.2.25 on 2025-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0020_alter_collaborators_files_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='identification_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil de nacimiento'), ('CE', 'Cédula de Extranjería'), ('P', 'Pasaporte')], default='CC', max_length=2, verbose_name='Tipo de Identificación'),
        ),
    ]
