# Generated by Django 3.2.25 on 2025-08-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0021_clients_identification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('familiar', 'Familiar'), ('personal', 'Personal')], max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Ocupación')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='terceros.clients')),
            ],
            options={
                'verbose_name': 'Referencia de Cliente',
                'verbose_name_plural': 'Referencias de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Client_employment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Empresa donde labora')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('profession', models.CharField(blank=True, max_length=255, verbose_name='Profesión')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Ocupación')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Salario/Ingresos Mensuales')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antigüedad (años)')),
                ('company_city', models.CharField(blank=True, max_length=255, verbose_name='Ciudad')),
                ('company_address', models.CharField(blank=True, max_length=500, verbose_name='Dirección')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono empresa')),
                ('social_organizations', models.TextField(blank=True, verbose_name='Entidades sociales, Deportivas, Culturales o Agremiaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='terceros.clients')),
            ],
            options={
                'verbose_name': 'Información Laboral de Cliente',
                'verbose_name_plural': 'Información Laboral de Clientes',
            },
        ),
    ]
