# Generated by Django 3.2.25 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0022_client_employment_info_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='clients',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad (texto)'),
        ),
        migrations.AddField(
            model_name='clients',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='País (texto)'),
        ),
        migrations.AddField(
            model_name='clients',
            name='lives_in_own_house',
            field=models.BooleanField(default=False, verbose_name='Vive en casa propia'),
        ),
        migrations.AddField(
            model_name='clients',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='clients',
            name='state_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Departamento (texto)'),
        ),
    ]
