# Generated by Django 3.2.25 on 2026-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0023_auto_20250813_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='cesantias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='eps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='pension',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
