# Generated by Django 3.2.9 on 2021-12-23 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcd_site', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id_property', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('m2_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Precio m2')),
                ('block', models.CharField(max_length=255, verbose_name='Manzana')),
                ('location', models.CharField(max_length=255, verbose_name='Lote')),
                ('stage', models.CharField(max_length=255, verbose_name='Etapa')),
                ('area', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Area')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('deed_date', models.DateField(verbose_name='Fecha de escritura')),
                ('state', models.CharField(choices=[('Libre', 'Libre'), ('Bloqueado', 'Bloqueado'), ('Reservado', 'Reservado'), ('Adjudicado', 'Adjudicado')], max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False, verbose_name='Número del contrato')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('comission_base', models.IntegerField(verbose_name='Comisión base')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Adjudicado', 'Adjudicado'), ('Anulado', 'Anulado'), ('Desistido', 'Desistido')], max_length=255, verbose_name='Estado')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('fisrt_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_owner', to='terceros.clients', verbose_name='Primer propietario')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
                ('property_sold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.properties', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Sales_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pago inicial')),
                ('to_finance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='A financiar')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='tasa de interés (mv)')),
            ],
            options={
                'verbose_name': 'Plan de venta',
                'verbose_name_plural': 'Planes de venta',
            },
        ),
        migrations.CreateModel(
            name='Sales_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales', verbose_name='Número de contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de venta',
                'verbose_name_plural': 'Historial de ventas',
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sales_plans', verbose_name='Plan de venta'),
        ),
        migrations.AddField(
            model_name='sales',
            name='second_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_owner', to='terceros.clients', verbose_name='Segundo propietario'),
        ),
        migrations.AddField(
            model_name='sales',
            name='third_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_owner', to='terceros.clients', verbose_name='Tercer propietario'),
        ),
        migrations.CreateModel(
            name='Payment_plans',
            fields=[
                ('id_payment', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id Cuota')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Interés corriente')),
                ('others', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Otros')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales', verbose_name='Número de contrato')),
            ],
            options={
                'verbose_name': 'Plan de pago',
                'verbose_name_plural': 'Planes de pago',
            },
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Adjudicado')), fields=('property_sold',), name='unique_property_sale'),
        ),
        migrations.AlterUniqueTogether(
            name='properties',
            unique_together={('description', 'project')},
        ),
    ]
