# Generated by Django 3.2.9 on 2021-12-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='fisrt_owner',
            new_name='first_owner',
        ),
    ]
