# Generated by Django 3.2.9 on 2021-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_fisrt_owner_sales_first_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='contract_number',
            field=models.IntegerField(default=1, verbose_name='Numero de contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='id_sale',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Venta'),
        ),
    ]
