# Generated by Django 3.2.9 on 2021-12-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0003_alter_counters_unique_together'),
        ('sales', '0003_auto_20211222_2313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sales',
            name='unique_property_sale',
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('project', 'contract_number')},
        ),
    ]
