# Generated by Django 3.2.9 on 2021-12-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20211222_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_plans',
            name='pay_date',
            field=models.DateField(default='2022-01-01', verbose_name='Fecha de pago'),
            preserve_default=False,
        ),
    ]
