# Generated by Django 3.2.9 on 2021-12-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_plans_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='observations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
