# Generated by Django 3.2.9 on 2021-12-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_plans',
            name='quota_type',
            field=models.CharField(default='CI', max_length=5),
            preserve_default=False,
        ),
    ]
