# Generated by Django 3.2.9 on 2021-12-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_payment_plans_quota_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission_position',
            fields=[
                ('id_charge', models.AutoField(primary_key=True, serialize=False, verbose_name='Id cargo')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje')),
                ('group', models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], help_text='Dependiendo del grupo escogido, el cargo se mostrará en la vista de asignaciones o no', max_length=255, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Cargo de comision',
                'verbose_name_plural': 'Cargos de comisiones',
            },
        ),
        migrations.AlterField(
            model_name='sales_history',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_id_history', to='sales.sales', verbose_name='Número de contrato'),
        ),
    ]
