# Generated by Django 3.2.9 on 2022-01-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0003_alter_counters_unique_together'),
        ('terceros', '0001_initial'),
        ('sales', '0008_auto_20211228_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_comission',
            fields=[
                ('id_asigned', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comision')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_asigned_comission', to='sales.comission_position', verbose_name='Comisiones asignadas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_asigned_comiss', to='mcd_site.projects', verbose_name='Proyecto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigned_comiss_sale', to='sales.sales', verbose_name='Venta')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_asigned', to='terceros.sellers', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comision asignada',
                'verbose_name_plural': 'Comisiones asignadas',
            },
        ),
    ]
