# Generated by Django 3.2.9 on 2022-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0005_timeline_project'),
        ('sales', '0009_assigned_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_plans',
            name='id_quota',
            field=models.CharField(default='A', max_length=255, unique=True, verbose_name='id Cuota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_plans',
            name='id_payment',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='payment_plans',
            unique_together={('id_quota', 'project')},
        ),
    ]
