# Generated by Django 3.2.9 on 2022-02-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0005_timeline_project'),
        ('sales', '0010_auto_20220118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_comission',
            name='id_comission',
            field=models.CharField(default='10CTR2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigned_comission',
            name='id_asigned',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='state',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Bloqueado', 'Bloqueado'), ('Asignado', 'Asignado')], max_length=255),
        ),
    ]
