# Generated by Django 3.2.9 on 2022-02-01 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_auto_20220131_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='prop_registry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='payment_plans',
            name='quota_type',
            field=models.CharField(max_length=5, verbose_name='Tipo de cuota'),
        ),
    ]
