# Generated by Django 3.2.9 on 2022-02-01 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0005_timeline_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_auto_20220131_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_plans',
            name='id_quota',
            field=models.CharField(max_length=255, verbose_name='id Cuota'),
        ),
        migrations.CreateModel(
            name='Paid_comissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='Fecha de pago')),
                ('comission', models.FloatField(verbose_name='Comision')),
                ('provision', models.FloatField(verbose_name='Provision')),
                ('net_payment', models.FloatField(verbose_name='Pago Neto')),
                ('assign_paid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assign_paid_comission', to='sales.assigned_comission', verbose_name='Comision asignada')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_comission_project', to='mcd_site.projects', verbose_name='Comisiones pagadas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_comission_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comision pagada',
                'verbose_name_plural': 'Comisiones pagadas',
            },
        ),
    ]
