# Generated by Django 3.2.9 on 2022-02-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20220131_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_comission',
            name='type_of_payment',
            field=models.CharField(choices=[('Anticipo', 'Anticipo'), ('30-30-40', '30-30-40'), ('50-50', '50-50')], default='Anticipo', max_length=255),
            preserve_default=False,
        ),
    ]
