# Generated by Django 3.2.9 on 2022-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_assigned_comission_type_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_comission',
            name='type_of_payment',
        ),
        migrations.AddField(
            model_name='paid_comissions',
            name='type_of_payment',
            field=models.CharField(choices=[('Anticipo', 'Anticipo'), ('30-30-40', '30-30-40'), ('50-50', '50-50')], default='sin pago', max_length=255),
            preserve_default=False,
        ),
    ]
