# Generated by Django 3.2.9 on 2022-02-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0006_auto_20220207_2151'),
        ('sales', '0015_auto_20220202_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup_payment_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('id_payment', models.IntegerField(verbose_name='id pago')),
                ('id_quota', models.CharField(max_length=255, verbose_name='id Cuota')),
                ('quota_type', models.CharField(max_length=5, verbose_name='Tipo de cuota')),
                ('pay_date', models.DateField(verbose_name='Fecha de pago')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Interés corriente')),
                ('others', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Otros')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcd_site.projects', verbose_name='Proyecto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales', verbose_name='Número de contrato')),
            ],
            options={
                'verbose_name': 'Plan de pago',
                'verbose_name_plural': 'Planes de pago',
                'unique_together': {('id_quota', 'project', 'backup_date')},
            },
        ),
    ]
