# Generated by Django 3.2.9 on 2022-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_backup_payment_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_payment_plans',
            name='backup_date',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
    ]
