# Generated by Django 3.2.9 on 2022-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_backup_payment_plans_backup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_comission',
            name='state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=255, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
