# Generated by Django 3.2.9 on 2022-02-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_assigned_comission_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_comission',
            name='state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=255, verbose_name='Estado'),
        ),
    ]
