# Generated by Django 3.2.13 on 2022-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_assigned_comission_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='stage',
            field=models.CharField(choices=[('PRIMERA', 'PRIMERA'), ('SEGUNDA', 'SEGUNDA'), ('TERCERA', 'TERCERA'), ('CUARTA', 'CUARTA'), ('QUINTA', 'QUINTA'), ('SEXTA', 'SEXTA'), ('SEPTIMA', 'SEPTIMA'), ('OCTAVA', 'OCTAVA'), ('NOVENA', 'NOVENA'), ('DECIMA', 'DECIMA')], max_length=255, verbose_name='Etapa'),
        ),
    ]
