# Generated by Django 3.2.13 on 2022-05-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0016_alter_collaborators_status'),
        ('sales', '0020_alter_properties_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission_position',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros.sellers', verbose_name='Asesor por defecto'),
        ),
    ]
