# Generated by Django 3.2.13 on 2022-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_comission_position_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_plans',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
