# Generated by Django 3.2.13 on 2022-05-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_sales_plans_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='deed_date',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='properties',
            name='stage',
            field=models.CharField(blank=True, choices=[('PRIMERA', 'PRIMERA'), ('SEGUNDA', 'SEGUNDA'), ('TERCERA', 'TERCERA'), ('CUARTA', 'CUARTA'), ('QUINTA', 'QUINTA'), ('SEXTA', 'SEXTA'), ('SEPTIMA', 'SEPTIMA'), ('OCTAVA', 'OCTAVA'), ('NOVENA', 'NOVENA'), ('DECIMA', 'DECIMA')], max_length=255, null=True, verbose_name='Etapa'),
        ),
    ]
