# Generated by Django 3.2.20 on 2023-08-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20220531_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterField(
            model_name='properties',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Area (en m2)'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='block',
            field=models.CharField(help_text='Esto corresponde, dependiendo del proyecto, a la manzana/vereda/bloque', max_length=255, verbose_name='Agrupador de lotes'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.CharField(help_text='Esta descripción es la forma en que este inmueble va a aparecer en TODOS los modulos e impresiones del sistema', max_length=255, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Numero de Lote'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='prop_registry',
            field=models.CharField(blank=True, help_text='Si no tiene matricula individual, ingresar la matricula del predio de mayor extensión', max_length=255, null=True, verbose_name='Matrícula Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='stage',
            field=models.CharField(blank=True, choices=[('PRIMERA', 'PRIMERA'), ('SEGUNDA', 'SEGUNDA'), ('TERCERA', 'TERCERA'), ('CUARTA', 'CUARTA'), ('QUINTA', 'QUINTA'), ('SEXTA', 'SEXTA'), ('SEPTIMA', 'SEPTIMA'), ('OCTAVA', 'OCTAVA'), ('NOVENA', 'NOVENA'), ('DECIMA', 'DECIMA')], max_length=255, null=True, verbose_name='Etapa de entrega'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='state',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Bloqueado', 'Bloqueado'), ('Asignado', 'Asignado')], help_text='Para un lote nuevo siempre debe ser Libre o Bloqueado, NUNCA seleccionar Asignado en este sitio', max_length=255),
        ),
    ]
