# Generated by Django 3.2.20 on 2023-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20230830_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='club',
            field=models.BooleanField(default=False, verbose_name='Club Mediterraneo'),
        ),
    ]
