# Generated by Django 3.2.20 on 2023-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_sales_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission_position',
            name='include_default',
            field=models.BooleanField(default=True, verbose_name='Incluir en escala automaticamente'),
        ),
    ]
