# Generated by Django 3.2.20 on 2023-09-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_comission_position_include_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission_position',
            name='advance_bonus',
            field=models.IntegerField(default=0, verbose_name='Monto para anticipos'),
        ),
    ]
