# Generated by Django 3.2.25 on 2025-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_comission_position_advance_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission_position',
            name='advance_bonus',
            field=models.IntegerField(default=0, verbose_name='Monto para anticipossales'),
        ),
    ]
