# Generated by Django 3.2.25 on 2025-07-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0021_clients_identification_type'),
        ('sales', '0028_alter_comission_position_advance_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='fourth_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth_owner', to='terceros.clients', verbose_name='Cuarto propietario'),
        ),
    ]
