# Generated by Django 3.2.25 on 2025-07-25 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0029_sales_fourth_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFiles',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Archivo')),
                ('description', models.CharField(help_text='Breve descripción del archivo cargado', max_length=255, verbose_name='Descripción del archivo')),
                ('file', models.FileField(help_text='Archivo asociado a la venta', upload_to='sales/files/', verbose_name='Archivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('file_type', models.CharField(blank=True, help_text='Tipo de archivo (ejemplo: contrato, factura, etc.)', max_length=50, null=True, verbose_name='Tipo de archivo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el archivo está activo o ha sido eliminado', verbose_name='Activo')),
                ('observations', models.TextField(blank=True, help_text='Comentarios adicionales sobre el archivo', null=True, verbose_name='Observaciones')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sales.sales', verbose_name='Venta')),
                ('uploaded_by', models.ForeignKey(help_text='Usuario que cargó el archivo', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Archivo de venta',
                'verbose_name_plural': 'Archivos de ventas',
                'ordering': ['-upload_date'],
            },
        ),
    ]
