# Generated by Django 3.2.25 on 2025-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0030_salesfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanRestructuring',
            fields=[
                ('id_restructuring', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructurings', to='sales.sales', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Reestructuración de plan de pagos',
                'verbose_name_plural': 'Reestructuraciones de planes de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanRestructuringDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quota', models.CharField(max_length=255, verbose_name='id Cuota')),
                ('quota_type', models.CharField(max_length=5, verbose_name='Tipo de cuota')),
                ('pay_date', models.DateField(verbose_name='Fecha de pago')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Interés corriente')),
                ('others', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Otros')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.paymentplanrestructuring')),
            ],
            options={
                'verbose_name': 'Detalle de reestructuración',
                'verbose_name_plural': 'Detalles de reestructuración',
            },
        ),
    ]
