# Generated by Django 3.2.25 on 2025-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_paymentplanrestructuring_paymentplanrestructuringdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanrestructuringdetail',
            name='tipo',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('split', 'Split'), ('nueva', 'Nueva'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Tipo de modificación'),
        ),
    ]
