# Generated by Django 3.2.25 on 2025-08-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0032_paymentplanrestructuringdetail_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanrestructuring',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplanrestructuring',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructurings_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
