# Generated by Django 3.2.25 on 2025-08-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_auto_20250808_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='sales',
            name='fecha_escrituracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de escrituración'),
        ),
    ]
