# Generated by Django 3.2.25 on 2025-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_auto_20250811_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='fecha_escrituracion',
        ),
        migrations.AddField(
            model_name='sales',
            name='actual_deed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real de escrituración'),
        ),
        migrations.AddField(
            model_name='sales',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real de entrega'),
        ),
        migrations.AddField(
            model_name='sales',
            name='deed_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de escritura'),
        ),
        migrations.AddField(
            model_name='sales',
            name='deed_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de escrituración'),
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AddField(
            model_name='sales',
            name='notary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Notaría'),
        ),
        migrations.AddField(
            model_name='sales',
            name='scheduled_deed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada de escrituración'),
        ),
        migrations.AddField(
            model_name='sales',
            name='scheduled_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada de entrega'),
        ),
    ]
