# Generated by Django 3.2.25 on 2025-08-20 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20250811_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanrestructuring',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Tasa de interés'),
        ),
        migrations.AddField(
            model_name='sales',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Tasa de interés'),
        ),
    ]
