# Generated by Django 3.2.25 on 2025-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20250820_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanrestructuring',
            name='nuevo_valor_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nuevo valor de venta'),
        ),
    ]
