# Generated by Django 3.2.25 on 2025-08-26 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0037_paymentplanrestructuring_nuevo_valor_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDetailsBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(help_text='Almacena en formato JSON los detalles de aplicaciones antes de desvincular', verbose_name='Detalles de aplicaciones')),
                ('motivo', models.TextField(help_text='Razón por la que se realizó la desvinculación de recaudos', verbose_name='Motivo de desvinculación')),
                ('backup_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del backup')),
                ('is_applied', models.BooleanField(default=False, help_text='Indica si este backup ya fue usado para restaurar aplicaciones', verbose_name='¿Fue aplicado nuevamente?')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_details_backups', to='sales.sales', verbose_name='Venta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_details_backups', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Backup de aplicaciones de recaudos',
                'verbose_name_plural': 'Backups de aplicaciones de recaudos',
                'ordering': ['-backup_date'],
            },
        ),
    ]
