# Generated by Django 3.2.25 on 2025-11-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_incomedetailsbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission_position',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
