# Generated by Django 3.2.25 on 2025-11-11 02:05

from django.db import migrations, models
import django.db.models.deletion


def copy_positions_to_projects(apps, schema_editor):
    Position = apps.get_model('sales', 'Comission_position')
    Project = apps.get_model('mcd_site', 'Projects')
    base_positions = list(Position.objects.filter(project__isnull=True))
    for project in Project.objects.all():
        for pos in base_positions:
            Position.objects.get_or_create(
                project=project,
                name=pos.name,
                defaults={
                    'rate': pos.rate,
                    'group': pos.group,
                    'default_id': pos.default_id,
                    'advance_bonus': pos.advance_bonus,
                    'include_default': pos.include_default,
                    'is_active': pos.is_active,
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0014_auto_20250721_2126'),
        ('sales', '0039_comission_position_is_active'),
    ]

    atomic = False

    operations = [
        migrations.AddField(
            model_name='comission_position',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comission_positions', to='mcd_site.projects', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='comission_position',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='comission_position',
            unique_together={('project', 'name')},
        ),
        migrations.RunPython(copy_positions_to_projects, migrations.RunPython.noop),
    ]
