# Generated by Django 3.2.25 on 2026-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd_site', '0014_auto_20250721_2126'),
        ('sales', '0040_auto_20251110_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='contract_prefix',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Prefijo contrato'),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('project', 'contract_prefix', 'contract_number')},
        ),
    ]
